TRADITIONAL_RECIPES = {
    "moqueca baiana": {"aliases":["moqueca","moqueca baiana"],"tags":["peixe","camarao","baiana","tradicional","dende","leite de coco"],"ingredients":["peixe firme em postas","tomate","cebola","pimentão","alho","coentro","leite de coco","azeite de dendê","limão","sal"],"steps":["Tempere o peixe com sal, limão e alho.","Monte camadas de cebola, tomate e pimentão numa panela larga.","Disponha o peixe, acrescente leite de coco e cozinhe sem mexer demais.","Finalize com dendê e coentro, ajustando sal."],"tips":"Não mexa vigorosamente para não quebrar o peixe. Camarão pode entrar no fim para não passar do ponto."},
    "moqueca capixaba": {"aliases":["moqueca capixaba"],"tags":["peixe","capixaba","tradicional","leve"],"ingredients":["peixe firme","tomate","cebola","alho","coentro","urucum ou colorau","azeite","limão","sal"],"steps":["Tempere o peixe.","Refogue levemente alho e urucum/colorau no azeite.","Monte peixe, tomate e cebola em camadas.","Cozinhe tampado até o peixe ficar macio e finalize com coentro."],"tips":"A versão capixaba tradicional não leva dendê nem leite de coco."},
    "vatapa": {"aliases":["vatapa","vatapá"],"tags":["baiana","tradicional","camarao","dende","leite de coco","pao"],"ingredients":["pão amanhecido ou farinha de trigo conforme a versão","leite de coco","camarão seco","amendoim","castanha de caju","cebola","gengibre","azeite de dendê","sal"],"steps":["Hidrate o pão no leite de coco e bata até formar creme.","Bata ou processe camarão seco, amendoim, castanha, cebola e gengibre.","Leve tudo ao fogo mexendo sempre até engrossar.","Finalize com dendê e ajuste o sal."],"tips":"Mexer constantemente evita que pegue no fundo. Há variações regionais importantes."},
    "baiao de dois": {"aliases":["baiao de dois","baião de dois"],"tags":["nordestina","tradicional","arroz","feijao","queijo coalho","carne seca"],"ingredients":["arroz","feijão-de-corda ou feijão verde cozido","carne-seca ou charque opcional","queijo coalho","cebola","alho","cheiro-verde","manteiga de garrafa ou óleo"],"steps":["Refogue carne-seca, cebola e alho.","Junte o arroz e parte do caldo do feijão.","Quando o arroz estiver quase pronto, acrescente o feijão.","Finalize com queijo coalho e cheiro-verde."],"tips":"Controle o caldo para o prato ficar úmido sem virar papa."},
    "acaraje": {"aliases":["acaraje","acarajé"],"tags":["baiana","tradicional","feijao fradinho","dende","salgado"],"ingredients":["feijão-fradinho","cebola","sal","azeite de dendê para fritar"],"steps":["Deixe o feijão de molho e retire o máximo possível das cascas.","Bata com cebola até obter massa firme e aerada.","Bata a massa por alguns minutos para incorporar ar.","Modele com colher e frite em dendê quente até dourar."],"tips":"Tradicionalmente é servido com vatapá, caruru, camarão seco e salada. A textura depende bastante de bater bem a massa."},
    "bobo de camarao": {"aliases":["bobo de camarao","bobó de camarão","bobo de camarão"],"tags":["baiana","tradicional","camarao","mandioca","leite de coco","dende"],"ingredients":["camarão","mandioca/aipim/macaxeira","leite de coco","tomate","cebola","alho","coentro","azeite de dendê","sal"],"steps":["Cozinhe a mandioca e bata com parte do caldo até virar creme.","Refogue cebola, alho e tomate.","Junte o creme de mandioca e leite de coco.","Acrescente o camarão perto do final e finalize com dendê e coentro."],"tips":"Camarão cozinha rápido; coloque no fim para não ficar borrachudo."},
    "feijao tropeiro": {"aliases":["feijao tropeiro","feijão tropeiro","tropeiro"],"tags":["mineira","tradicional","feijao","farinha","linguica","bacon"],"ingredients":["feijão cozido e escorrido","farinha de mandioca","bacon","linguiça","ovos","couve","cebola","alho","cheiro-verde"],"steps":["Doure bacon e linguiça.","Refogue cebola, alho e couve.","Junte os ovos e mexa.","Acrescente feijão e farinha aos poucos, finalizando com cheiro-verde."],"tips":"O feijão deve estar firme e bem escorrido."},
    "galinhada": {"aliases":["galinhada"],"tags":["goiana","mineira","tradicional","frango","arroz","panela"],"ingredients":["frango em pedaços","arroz","cebola","alho","tomate","açafrão-da-terra","cheiro-verde","óleo","sal"],"steps":["Doure bem o frango.","Refogue cebola, alho e tomate.","Junte arroz e açafrão-da-terra.","Adicione água e cozinhe tudo junto até o arroz ficar macio."],"tips":"O fundo dourado da panela dá bastante sabor ao arroz."},
    "barreado": {"aliases":["barreado"],"tags":["paranaense","tradicional","carne","cozimento longo","mandioca"],"ingredients":["carne bovina em cubos ou tiras","cebola","alho","cominho","louro","bacon opcional","água","farinha de mandioca para servir"],"steps":["Tempere e acomode carne e temperos numa panela pesada.","Cozinhe lentamente por várias horas até a carne desmanchar.","Ajuste o caldo e desfie a carne no próprio molho.","Sirva com farinha de mandioca e, tradicionalmente, banana."],"tips":"O prato tradicional usa panela vedada; em casa, panela de pressão é uma adaptação prática."},
    "cuscuz nordestino": {"aliases":["cuscuz","cuscuz nordestino","cuscuz de milho"],"tags":["nordestina","tradicional","milho","cafe da manha","simples"],"ingredients":["flocão de milho","água","sal","manteiga opcional"],"steps":["Misture o flocão com água e sal e deixe hidratar por alguns minutos.","Coloque na cuscuzeira sem compactar demais.","Cozinhe no vapor até ficar firme e macio.","Sirva com manteiga ou acompanhamentos."],"tips":"Vai bem com ovo, queijo coalho, carne-seca, leite ou café, dependendo da região e do gosto."},
    "caruru": {"aliases":["caruru"],"tags":["baiana","tradicional","quiabo","dende","camarao seco"],"ingredients":["quiabo","camarão seco","cebola","amendoim","castanha de caju","azeite de dendê","gengibre opcional","sal"],"steps":["Corte o quiabo bem pequeno.","Bata camarão seco, cebola, amendoim e castanha.","Cozinhe o quiabo com a mistura até ficar macio.","Finalize com dendê e ajuste o sal."],"tips":"O ponto pode variar bastante entre receitas familiares e regionais."},
    "vaca atolada": {"aliases":["vaca atolada"],"tags":["mineira","tradicional","costela","mandioca","panela"],"ingredients":["costela bovina","mandioca/aipim/macaxeira","cebola","alho","tomate","cheiro-verde","sal","pimenta"],"steps":["Doure a costela.","Refogue cebola, alho e tomate.","Cozinhe a costela até começar a ficar macia.","Junte mandioca e cozinhe até ela quase desmanchar e engrossar o caldo."],"tips":"É justamente a mandioca se desfazendo que deixa o caldo espesso."},
}
