"""Acervo culinário amplo do Butler, organizado por áreas.

Cada entrada é dado consultável, não regra de conversa. O roteador usa categoria,
aliases, ingredientes, tags e contexto para encontrar opções.
"""

COOKING_BOOKS = {
    "massas": {
        "aliases": ["massa", "massas", "macarrao", "macarrão", "pasta"],
        "recipes": {
            "carbonara": {"aliases":["carbonara","macarrao carbonara","macarrão carbonara"],"tags":["massa","macarrao","rapido","cremoso"],"ingredients":["macarrão","ovos","queijo parmesão ou pecorino","bacon ou guanciale","pimenta-do-reino","sal"],"steps":["Cozinhe a massa até ficar al dente e reserve um pouco da água do cozimento.","Doure o bacon/guanciale e desligue o fogo.","Misture ovos, queijo ralado e pimenta numa tigela.","Junte a massa quente à carne e incorpore a mistura de ovos fora do fogo, ajustando com água do cozimento até ficar cremosa."],"tips":"O molho clássico não leva creme de leite; o calor residual cozinha os ovos sem virar omelete."},
            "macarrao a bolonhesa": {"aliases":["bolonhesa","macarrao bolonhesa","macarrão à bolonhesa"],"tags":["massa","macarrao","carne moida","molho"],"ingredients":["macarrão","carne moída","cebola","alho","molho de tomate","azeite","sal","pimenta"],"steps":["Refogue cebola e alho.","Doure a carne moída.","Junte molho de tomate e cozinhe até encorpar.","Misture ou sirva sobre a massa cozida."],"tips":"Um pouco da água da massa ajuda o molho a aderir."},
            "alho e oleo": {"aliases":["alho e oleo","alho e óleo","macarrao alho e oleo"],"tags":["massa","macarrao","rapido","barato"],"ingredients":["macarrão","alho","azeite ou óleo","sal","salsinha opcional"],"steps":["Cozinhe a massa al dente.","Doure levemente o alho no azeite sem queimar.","Misture a massa e um pouco da água do cozimento.","Finalize com salsinha."],"tips":"Alho queimado amarga; fogo médio-baixo resolve."},
            "molho branco": {"aliases":["macarrao molho branco","macarrão com molho branco","bechamel"],"tags":["massa","macarrao","cremoso","molho"],"ingredients":["macarrão","manteiga","farinha de trigo","leite","sal","noz-moscada","queijo opcional"],"steps":["Derreta manteiga e misture a farinha por cerca de 1 minuto.","Adicione leite aos poucos mexendo sempre.","Tempere e cozinhe até engrossar.","Misture à massa cozida."],"tips":"Leite aos poucos evita grumos."},
            "lasanha bolonhesa": {"aliases":["lasanha","lasanha bolonhesa"],"tags":["massa","forno","carne moida","queijo"],"ingredients":["massa de lasanha","carne moída","molho de tomate","muçarela","presunto opcional","cebola","alho"],"steps":["Prepare um molho bolonhesa.","Monte camadas de molho, massa e queijo.","Repita até preencher o refratário.","Asse até borbulhar e gratinar."],"tips":"Molho suficiente evita massa seca."},
            "nhoque de batata": {"aliases":["nhoque","nhoque de batata"],"tags":["massa","batata","molho","caseiro"],"ingredients":["batata","farinha de trigo","gema opcional","sal","molho de tomate"],"steps":["Cozinhe e amasse as batatas ainda quentes.","Misture farinha aos poucos até dar ponto sem sovar demais.","Modele rolinhos, corte e cozinhe em água fervente.","Retire quando subirem e sirva com molho."],"tips":"Quanto menos farinha, mais leve o nhoque."},
        },
    },
    "carnes": {
        "aliases": ["carne", "carnes", "bife", "carne bovina"],
        "recipes": {
            "carne de panela": {"aliases":["carne de panela","carne cozida","carne na pressao","carne na pressão"],"tags":["carne","panela","pressao","batata","almoco"],"ingredients":["acém ou músculo em cubos","cebola","alho","tomate ou molho de tomate","batata","óleo","sal","pimenta","água"],"steps":["Sele a carne em etapas até dourar.","Refogue cebola e alho e junte tomate.","Cubra parcialmente com água e cozinhe na pressão por cerca de 25–35 minutos.","Abra, junte batata e cozinhe sem pressão até ficar macia e o molho encorpar."],"tips":"Acém e músculo ficam ótimos em cozimento longo."},
            "bife acebolado": {"aliases":["bife","bife acebolado","bife de carne"],"tags":["carne","bife","frigideira","rapido"],"ingredients":["bifes de patinho, alcatra ou coxão mole","cebola","óleo ou manteiga","sal","pimenta"],"steps":["Seque e tempere os bifes.","Aqueça bem a frigideira e sele os bifes sem lotar a panela.","Reserve e refogue a cebola na mesma frigideira.","Volte os bifes rapidamente e sirva."],"tips":"Frigideira bem quente ajuda a dourar sem cozinhar demais."},
            "picadinho": {"aliases":["picadinho","picadinho de carne"],"tags":["carne","panela","molho","arroz"],"ingredients":["carne em cubos pequenos","cebola","alho","tomate","molho inglês opcional","óleo","sal","pimenta"],"steps":["Doure a carne.","Junte cebola e alho.","Adicione tomate e um pouco de água.","Cozinhe até a carne ficar macia e o molho reduzir."],"tips":"Vai bem com arroz, feijão, farofa e ovo."},
            "carne moida refogada": {"aliases":["carne moida","carne moída","carne moida refogada"],"tags":["carne","carne moida","rapido","panela"],"ingredients":["carne moída","cebola","alho","tomate","óleo","sal","pimenta","cheiro-verde"],"steps":["Doure a carne sem mexer demais no início.","Junte cebola e alho.","Acrescente tomate e temperos.","Reduza a umidade e finalize com cheiro-verde."],"tips":"Serve como base para recheios, escondidinho e molho."},
            "almondegas": {"aliases":["almondega","almôndega","almondegas","almôndegas"],"tags":["carne moida","molho","massa"],"ingredients":["carne moída","ovo","farinha de rosca","cebola","alho","sal","pimenta","molho de tomate"],"steps":["Misture carne, ovo, farinha e temperos.","Modele bolas sem apertar demais.","Doure e finalize cozinhando no molho."],"tips":"Não compacte demais para não ficar seca."},
        },
    },
    "salgados": {
        "aliases": ["salgado", "salgados", "lanche salgado"],
        "recipes": {
            "coxinha": {"aliases":["coxinha","coxinha de frango"],"tags":["salgado","frango","frito","festa"],"ingredients":["frango cozido e desfiado","caldo do cozimento","farinha de trigo","manteiga","cebola","alho","requeijão opcional","ovo","farinha de rosca","óleo"],"steps":["Refogue e tempere o frango.","Ferva caldo com manteiga e acrescente farinha de uma vez, mexendo até a massa soltar da panela.","Esfrie, recheie e modele.","Empane e frite até dourar."],"tips":"Massa morna é mais fácil de modelar."},
            "pastel": {"aliases":["pastel","pastel caseiro"],"tags":["salgado","frito","lanche","recheio"],"ingredients":["massa de pastel","recheio a gosto","óleo"],"steps":["Distribua o recheio sem exagerar.","Umedeça levemente as bordas e feche apertando com garfo.","Frite em óleo quente até dourar."],"tips":"Recheio muito úmido pode abrir o pastel."},
            "empada de frango": {"aliases":["empada","empada de frango"],"tags":["salgado","frango","forno","massa"],"ingredients":["farinha de trigo","manteiga","gema","sal","frango desfiado","cebola","tomate","requeijão opcional"],"steps":["Misture farinha, manteiga, gema e sal sem sovar muito.","Prepare o recheio de frango e deixe esfriar.","Forre forminhas, recheie e cubra.","Pincele gema e asse até dourar."],"tips":"Recheio frio evita derreter a massa antes do forno."},
            "esfiha aberta": {"aliases":["esfiha","esfiha aberta"],"tags":["salgado","forno","carne moida","massa"],"ingredients":["farinha de trigo","fermento biológico","água","óleo","sal","carne moída","tomate","cebola","limão"],"steps":["Prepare e deixe a massa crescer.","Tempere a carne com tomate, cebola e limão e escorra excesso de líquido.","Abra discos, distribua o recheio e asse em forno alto."],"tips":"Recheio menos úmido deixa a massa melhor assada."},
            "pao de queijo": {"aliases":["pao de queijo","pão de queijo"],"tags":["salgado","forno","queijo","lanche"],"ingredients":["polvilho","leite","óleo","ovos","queijo curado ou parmesão","sal"],"steps":["Escalde o polvilho com leite e óleo quentes.","Espere amornar e misture ovos e queijo.","Modele bolinhas e asse até crescer e dourar."],"tips":"A massa deve ficar pegajosa, mas modelável com mãos untadas."},
        },
    },
    "arroz e feijao": {
        "aliases": ["arroz", "feijao", "feijão", "arroz e feijao", "arroz e feijão"],
        "recipes": {
            "arroz branco": {"aliases":["arroz","arroz branco","arroz soltinho"],"tags":["arroz","basico","acompanhamento"],"ingredients":["arroz","água","alho","óleo","sal"],"steps":["Refogue o alho no óleo.","Junte o arroz e refogue por 1 minuto.","Adicione água quente e sal.","Cozinhe em fogo baixo até secar e descansar tampado por alguns minutos."],"tips":"Evite mexer durante o cozimento para ficar mais soltinho."},
            "arroz carreteiro": {"aliases":["arroz carreteiro","carreteiro"],"tags":["arroz","carne","aproveitamento","panela"],"ingredients":["arroz","carne seca ou carne assada picada","cebola","alho","tomate","cheiro-verde"],"steps":["Doure/refogue a carne.","Junte cebola, alho e tomate.","Adicione arroz e água e cozinhe até secar.","Finalize com cheiro-verde."],"tips":"Ótimo para aproveitar sobra de carne."},
            "bolinho de arroz": {"aliases":["bolinho de arroz","resto de arroz","sobra de arroz","arroz de ontem"],"tags":["arroz","aproveitamento","frito","salgado"],"ingredients":["arroz cozido","ovo","farinha de trigo ou amido","queijo opcional","cheiro-verde","sal","óleo"],"steps":["Misture o arroz com ovo, farinha e temperos.","Modele porções com colher.","Frite ou asse até dourar."],"tips":"Queijo ralado ajuda sabor e liga."},
            "arroz de forno": {"aliases":["arroz de forno","sobra de arroz","resto de arroz"],"tags":["arroz","aproveitamento","forno","queijo"],"ingredients":["arroz cozido","molho de tomate","presunto opcional","muçarela","milho","ervilha","frango ou carne opcional"],"steps":["Misture o arroz com molho e complementos.","Passe para um refratário e cubra com queijo.","Asse até aquecer e gratinar."],"tips":"Funciona muito bem com sobras da geladeira."},
            "feijao simples": {"aliases":["feijao","feijão","feijao simples","feijão simples"],"tags":["feijao","basico","panela de pressao"],"ingredients":["feijão","água","alho","óleo","sal","louro opcional"],"steps":["Escolha e lave o feijão.","Cozinhe na pressão com água e louro até ficar macio.","Refogue alho no óleo, junte parte do feijão e amasse alguns grãos.","Volte tudo à panela, ajuste sal e ferva até engrossar."],"tips":"O tempo varia com o tipo e idade do feijão."},
            "tutu de feijao": {"aliases":["tutu","tutu de feijao","tutu de feijão"],"tags":["feijao","aproveitamento","farinha","brasileira"],"ingredients":["feijão cozido com caldo","farinha de mandioca","alho","cebola","bacon opcional","sal"],"steps":["Refogue alho, cebola e bacon.","Junte o feijão e aqueça.","Adicione farinha aos poucos mexendo até engrossar."],"tips":"Farinha entra aos poucos; engrossa rápido."},
        },
    },
    "legumes": {
        "aliases": ["legume", "legumes", "verduras", "vegetais"],
        "recipes": {
            "legumes salteados": {"aliases":["legumes salteados","legumes refogados","legumes na frigideira"],"tags":["legumes","leve","rapido","frigideira"],"ingredients":["cenoura","abobrinha","brócolis","cebola","azeite","sal","pimenta"],"steps":["Corte os legumes em tamanhos parecidos.","Aqueça bem a frigideira com azeite.","Salteie começando pelos mais firmes.","Tempere e preserve alguma crocância."],"tips":"Não lote a frigideira para evitar que cozinhem no vapor."},
            "legumes assados": {"aliases":["legumes assados","legumes no forno"],"tags":["legumes","forno","leve","acompanhamento"],"ingredients":["batata","cenoura","abobrinha","cebola","azeite","sal","ervas"],"steps":["Corte os legumes.","Misture com azeite, sal e ervas.","Espalhe sem amontoar e asse em forno alto até dourar."],"tips":"Peças do mesmo tamanho assam por igual."},
            "sopa de legumes": {"aliases":["sopa de legumes","sopa de verdura"],"tags":["legumes","sopa","leve","panela"],"ingredients":["batata","cenoura","abóbora","chuchu","cebola","alho","água ou caldo","sal"],"steps":["Refogue cebola e alho.","Junte legumes e cubra com água/caldo.","Cozinhe até ficarem macios.","Sirva em pedaços ou bata parte para engrossar."],"tips":"Pode receber frango desfiado ou macarrão pequeno."},
        },
    },
    "saladas": {
        "aliases": ["salada", "saladas", "algo leve"],
        "recipes": {
            "salada simples": {"aliases":["salada simples","salada verde"],"tags":["salada","leve","cru","rapido"],"ingredients":["alface","tomate","cebola","azeite","limão ou vinagre","sal"],"steps":["Lave e seque os vegetais.","Corte e misture.","Tempere apenas na hora de servir."],"tips":"Secar bem as folhas ajuda o molho a aderir."},
            "salada de grao de bico": {"aliases":["salada de grao de bico","salada de grão-de-bico"],"tags":["salada","grao de bico","proteina","leve"],"ingredients":["grão-de-bico cozido","tomate","cebola roxa","pepino","salsinha","azeite","limão","sal"],"steps":["Misture todos os ingredientes frios.","Tempere com azeite, limão e sal.","Descanse alguns minutos antes de servir."],"tips":"Fica melhor gelada e aguenta bem na geladeira."},
            "salada de batata": {"aliases":["salada de batata","maionese de batata"],"tags":["salada","batata","maionese","acompanhamento"],"ingredients":["batata","cenoura opcional","maionese","cebola","cheiro-verde","sal"],"steps":["Cozinhe a batata até ficar macia sem desmanchar.","Esfrie completamente.","Misture com os demais ingredientes e leve à geladeira."],"tips":"Misturar quente deixa a maionese pesada e pode desmanchar a batata."},
        },
    },
    "frango": {
        "aliases": ["frango", "peito de frango", "coxa", "sobrecoxa"],
        "recipes": {
            "frango grelhado": {"aliases":["frango grelhado","peito de frango"],"tags":["frango","leve","rapido","frigideira"],"ingredients":["filés de frango","alho","limão","sal","pimenta","azeite"],"steps":["Tempere o frango.","Aqueça bem a frigideira.","Grelhe sem mexer até dourar e vire.","Descanse antes de cortar."],"tips":"Filés de espessura parecida cozinham por igual."},
            "frango assado": {"aliases":["frango assado","coxa assada","sobrecoxa assada"],"tags":["frango","forno","almoco"],"ingredients":["coxas/sobrecoxas","alho","limão","paprica","sal","pimenta","azeite"],"steps":["Tempere e deixe pegar gosto se houver tempo.","Disponha sem amontoar.","Asse até dourar e atingir cozimento completo."],"tips":"Pele para cima ajuda a ficar crocante."},
            "strogonoff de frango": {"aliases":["strogonoff de frango","estrogonofe de frango"],"tags":["frango","cremoso","rapido"],"ingredients":["frango em cubos","cebola","alho","ketchup","mostarda","creme de leite","sal","pimenta"],"steps":["Doure o frango em etapas.","Refogue cebola e alho.","Junte ketchup e mostarda.","Finalize com creme de leite em fogo baixo."],"tips":"Evite ferver forte depois do creme de leite."},
            "frango xadrez": {"aliases":["frango xadrez"],"tags":["frango","legumes","shoyu","panela"],"ingredients":["frango em cubos","cebola","pimentão","cenoura","shoyu","amido de milho","óleo"],"steps":["Doure o frango.","Salteie os legumes.","Junte shoyu com água e amido.","Cozinhe até o molho encorpar."],"tips":"Amendoim torrado pode entrar no final."},
        },
    },
    "doces e bolos": {
        "aliases": ["doce", "doces", "bolo", "bolos", "sobremesa", "sobremesas"],
        "recipes": {
            "bolo simples": {"aliases":["bolo","bolo simples","bolo caseiro"],"tags":["bolo","doce","forno"],"ingredients":["ovos","açúcar","farinha de trigo","leite","manteiga","fermento"],"steps":["Bata ovos, açúcar e manteiga.","Junte leite e farinha aos poucos.","Misture fermento por último.","Asse a 180 °C até o palito sair limpo."],"tips":"Base boa para adicionar coco, laranja ou chocolate."},
            "brigadeiro": {"aliases":["brigadeiro"],"tags":["doce","chocolate","panela","rapido"],"ingredients":["leite condensado","chocolate em pó","manteiga","granulado opcional"],"steps":["Misture tudo em fogo baixo.","Mexa sem parar até desgrudar do fundo para enrolar ou deixe um pouco antes para comer de colher."],"tips":"Fogo baixo dá mais controle do ponto."},
            "pudim de leite": {"aliases":["pudim","pudim de leite","pudim de leite condensado"],"tags":["sobremesa","forno","leite condensado"],"ingredients":["leite condensado","leite","ovos","açúcar para caramelo"],"steps":["Faça o caramelo e espalhe na forma.","Bata suavemente leite condensado, leite e ovos.","Asse em banho-maria até firmar.","Gele bem antes de desenformar."],"tips":"Bater pouco reduz bolhas no pudim."},
        },
    },
}
