"""Conhecimento culinário sobre cortes e preparações de carnes.

Diferencia corte bovino de carne curada/preparada e associa cada item a usos
culinários para a Library conseguir responder tanto "o que é?" quanto sugerir pratos.
"""

MEAT_CUTS = {
    "file mignon": {"aliases":["file mignon","filé mignon","file mingnon","filé mingnon","mignon"],"kind":"corte bovino","profile":"Muito macio, magro e de sabor delicado.","best_for":["medalhao","bife","strogonoff","iscas","molho madeira"],"cooking":"Fogo alto e preparo curto; evite cozinhar demais."},
    "contrafile": {"aliases":["contrafile","contrafilé","contra file","contra filé"],"kind":"corte bovino","profile":"Macio, saboroso e com capa de gordura característica.","best_for":["bife","churrasco","grelhado","acebolado"],"cooking":"Grelha ou frigideira bem quente."},
    "alcatra": {"aliases":["alcatra"],"kind":"corte bovino","profile":"Versátil, relativamente macio e equilibrado em gordura.","best_for":["bife","churrasco","picadinho","iscas"],"cooking":"Vai bem em preparos rápidos ou cubos."},
    "picanha": {"aliases":["picanha"],"kind":"corte bovino","profile":"Sabor marcante e capa de gordura importante para o preparo.","best_for":["churrasco","forno","frigideira"],"cooking":"Evite retirar toda a gordura antes de assar ou grelhar."},
    "patinho": {"aliases":["patinho"],"kind":"corte bovino","profile":"Corte relativamente magro e versátil.","best_for":["carne moida","bife","almondega","quibe","picadinho"],"cooking":"Bom para moer ou preparos rápidos em bifes finos."},
    "acem": {"aliases":["acem","acém"],"kind":"corte bovino","profile":"Saboroso, com fibras que ficam macias em cozimento mais longo.","best_for":["carne de panela","carne moida","ensopado","picadinho"],"cooking":"Pressão, panela lenta ou cozimento úmido."},
    "musculo": {"aliases":["musculo","músculo","musculo bovino","músculo bovino"],"kind":"corte bovino","profile":"Rico em tecido conjuntivo e colágeno; fica muito macio e encorpado com tempo.","best_for":["carne de panela","ensopado","sopa","caldo","ragu"],"cooking":"Cozimento longo ou pressão. Excelente para caldos."},
    "costela": {"aliases":["costela","costela bovina"],"kind":"corte bovino","profile":"Gordurosa, muito saborosa e rica em colágeno.","best_for":["churrasco","forno","panela de pressao","costela com mandioca"],"cooking":"Baixa temperatura e tempo longo ou pressão."},
    "cupim": {"aliases":["cupim"],"kind":"corte bovino","profile":"Corte entremeado de gordura, intenso e muito macio quando bem cozido.","best_for":["churrasco","forno","panela de pressao"],"cooking":"Precisa de tempo para a gordura e o colágeno amaciarem a carne."},
    "coxao mole": {"aliases":["coxao mole","coxão mole"],"kind":"corte bovino","profile":"Macio e versátil.","best_for":["bife","bife a role","escalope","picadinho"],"cooking":"Bom para frigideira e preparos médios."},
    "coxao duro": {"aliases":["coxao duro","coxão duro"],"kind":"corte bovino","profile":"Mais firme e fibroso.","best_for":["carne de panela","carne recheada","ensopado"],"cooking":"Prefira pressão ou cozimento longo."},
    "lagarto": {"aliases":["lagarto"],"kind":"corte bovino","profile":"Magro, firme e de formato uniforme.","best_for":["carne assada","carne de panela","rosbife","carne louca"],"cooking":"Controle o ponto em assados; pressão funciona para preparos desfiados."},
    "fraldinha": {"aliases":["fraldinha"],"kind":"corte bovino","profile":"Fibras longas, bastante sabor e boa suculência.","best_for":["churrasco","forno","grelhado"],"cooking":"Corte contra as fibras ao servir."},
    "maminha": {"aliases":["maminha"],"kind":"corte bovino","profile":"Macia, suculenta e de sabor moderado.","best_for":["churrasco","forno","panela"],"cooking":"Boa inteira assada ou em bifes grossos."},
    "peito bovino": {"aliases":["peito bovino","peito de boi","brisket"],"kind":"corte bovino","profile":"Fibroso, rico em colágeno e muito saboroso após cozimento prolongado.","best_for":["panela","defumado","ensopado","carne desfiada"],"cooking":"Tempo longo e temperatura baixa ou pressão."},
    "ossobuco": {"aliases":["ossobuco","osso buco"],"kind":"corte bovino com osso","profile":"Fatia transversal do músculo/canela com osso e tutano no centro.","best_for":["ensopado","molho","cozimento lento"],"cooking":"Cozimento úmido e longo aproveita colágeno e tutano."},
    "tutano": {"aliases":["tutano","tutano bovino","tutano de boi"],"kind":"medula óssea","profile":"Parte gordurosa e muito saborosa encontrada dentro de ossos bovinos; não é propriamente um corte muscular.","best_for":["tutano assado","caldo","molho","finalizacao"],"cooking":"Pode ser assado no osso ou usado para enriquecer caldos e molhos."},
    "carne do sol": {"aliases":["carne do sol","carne-de-sol","carne de sol"],"kind":"carne bovina salgada e parcialmente desidratada","profile":"Preparação tradicional muito associada ao Nordeste brasileiro; sabor concentrado e salgado.","best_for":["carne do sol acebolada","carne do sol com aipim","escondidinho","paçoca de carne"],"cooking":"Dependendo do produto, dessalgue antes. Fica ótima grelhada ou acebolada."},
    "charque": {"aliases":["charque","carne seca","carne-seca","jabá","jaba","carne de jaba","carne de jabá"],"kind":"carne bovina salgada e desidratada","profile":"Carne conservada por salga e secagem, mais intensa e seca que carne do sol. 'Jabá' é um nome popular/regional associado a carne-seca/charque.","best_for":["feijao","feijoada","escondidinho","arroz carreteiro","carne seca acebolada","paçoca"],"cooking":"Normalmente precisa dessalgar e cozinhar antes de desfiar ou refogar."},
}

MEAT_RECIPES = {
    "file mignon ao molho madeira": {"aliases":["file mignon molho madeira","filé mignon ao molho madeira","mignon ao molho madeira"],"tags":["carne","file mignon","frigideira","molho"],"ingredients":["filé mignon em medalhões ou bifes","sal","pimenta-do-reino","manteiga ou óleo","cebola opcional","molho madeira ou caldo de carne reduzido","champignon opcional"],"steps":["Tempere e sele o filé mignon em frigideira bem quente.","Reserve a carne.","Na mesma frigideira prepare ou aqueça o molho, soltando o fundo dourado.","Volte a carne apenas o suficiente para aquecer e sirva."],"tips":"O filé mignon perde maciez se ficar tempo demais no fogo."},
    "carne do sol acebolada": {"aliases":["carne do sol","carne do sol acebolada","carne de sol acebolada"],"tags":["carne","carne do sol","nordestina","frigideira","cebola"],"ingredients":["carne do sol","cebola em rodelas","manteiga de garrafa ou óleo","alho opcional"],"steps":["Prove a carne e dessalgue se necessário.","Corte e doure a carne em frigideira quente.","Reserve e refogue bastante cebola na mesma gordura.","Misture a carne e finalize."],"tips":"Vai muito bem com aipim/macaxeira, feijão verde, arroz e farofa."},
    "carne seca acebolada": {"aliases":["carne seca acebolada","charque acebolado","jaba acebolado","jabá acebolado"],"tags":["carne","charque","carne seca","jaba","cebola"],"ingredients":["charque ou carne-seca","cebola","óleo ou manteiga de garrafa","alho opcional"],"steps":["Dessalgue a carne trocando a água conforme necessário.","Cozinhe até ficar macia e corte ou desfie.","Doure rapidamente e junte cebola em rodelas.","Refogue até a cebola amaciar."],"tips":"A etapa de dessalga varia bastante conforme a carne comprada; prove antes de corrigir sal."},
    "musculo na pressao": {"aliases":["musculo na pressao","músculo na pressão","musculo de panela"],"tags":["carne","musculo","panela de pressao","molho"],"ingredients":["músculo em cubos","cebola","alho","tomate","óleo","sal","pimenta","água","batata ou cenoura opcional"],"steps":["Sele o músculo até dourar.","Refogue cebola, alho e tomate.","Adicione água sem cobrir excessivamente e cozinhe na pressão até ficar macio.","Junte legumes, se quiser, e finalize sem pressão até o caldo encorpar."],"tips":"O colágeno do músculo deixa o molho naturalmente encorpado."},
    "tutano assado": {"aliases":["tutano assado","tutano no forno"],"tags":["carne","tutano","forno","entrada"],"ingredients":["ossos bovinos com tutano cortados longitudinalmente ou em rodelas","sal","pimenta","pão para servir opcional"],"steps":["Disponha os ossos numa assadeira com o tutano voltado para cima.","Tempere levemente.","Asse em forno alto até o tutano ficar macio e borbulhante, sem deixar derreter completamente.","Sirva imediatamente."],"tips":"É bastante rico em gordura; pequenas porções costumam bastar."},
    "escondidinho de carne seca": {"aliases":["escondidinho de carne seca","escondidinho de charque","escondidinho de jaba","escondidinho de jabá"],"tags":["carne","charque","carne seca","mandioca","forno"],"ingredients":["carne-seca ou charque dessalgado e desfiado","mandioca/aipim/macaxeira","leite","manteiga","cebola","queijo opcional"],"steps":["Cozinhe a mandioca e faça um purê com leite e manteiga.","Refogue a carne dessalgada e desfiada com cebola.","Monte carne e purê em camadas.","Cubra com queijo, se quiser, e gratine."],"tips":"A carne precisa estar bem dessalgada antes da montagem."},
}
