# Configuração pública da implantação do Butler.
# O TELEGRAM_BOT_TOKEN continua sendo o único secret obrigatório no Worker.

OWNER_CHAT_ID = 7882764998
OWNER_PREFERRED_NAME = "Gabriel"
TIMEZONE_NAME = "America/Bahia"
UTC_OFFSET_HOURS = -3

MORNING_SUMMARY_HOUR = 7
MORNING_SUMMARY_MINUTE = 30
WEEKLY_SUMMARY_WEEKDAY = 6
WEEKLY_SUMMARY_HOUR = 20
WEEKLY_SUMMARY_MINUTE = 0
